name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          npm install
      - name: Lint check
        run: |
          npm run lint
      - name: Test check
        run: |
          npm run test
      - name: Deploy
        run: |
          git config --global user.name 'Vadim Kasatkin'
          git config --global user.email 'penguin-astronaut@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
