name: PR Sanity Check

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          npm install
      - name: Lint check
        run: |
          npm run lint
      - name: Test check
        run: |
          npm run test
      - name: Deploy dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: penguin-astronaut/weather-app/
          event-type: deploy-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
